// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct/session connection (port 5432), not the
    // transaction pooler. Falls back to DATABASE_URL if DIRECT_URL is unset.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
