// Evergreen exam-overview copy for the /exams/[slug] landing pages (SEO + student trust).

export type ExamIntro = {
  examSlug: string;
  heading: string;
  paragraphs: string[];
  pattern: { label: string; value: string }[];
  topics: string[];
  tips: string[];
};

export const examIntros: ExamIntro[] = [
  {
    examSlug: "ssc-cgl",
    heading: "SSC CGL & Banking: Your Gateway to a Government Job",
    paragraphs: ["The SSC Combined Graduate Level (CGL) exam is conducted by the Staff Selection Commission to recruit graduates into Group B and Group C posts across ministries, departments, and offices of the Government of India. Popular posts include Income Tax Inspector, Assistant Section Officer, and Auditor. Alongside SSC CGL, lakhs of aspirants prepare for banking exams like IBPS PO, IBPS Clerk, and SBI PO, which share a very similar aptitude-based syllabus.","Anyone who has completed a bachelor's degree can appear, and the exam draws millions of candidates every year, making it one of India's most competitive recruitment routes. The selection is staged: Tier-1 is a common objective screening test, followed by Tier-2, which is more specialised.","On PadhoDost you can take free full-length Tier-1 mock tests that mirror the real timing and marking, drill individual sections like Quant and Reasoning through chapter-wise practice, and see your All-India rank against other aspirants. Visual explainers break down tricky topics such as time-and-work, data interpretation, and syllogisms so concepts actually stick."],
    pattern: [{"label":"Total questions","value":"100 (Tier-1)"},{"label":"Total marks","value":"200"},{"label":"Duration","value":"60 minutes"},{"label":"Marking","value":"+2 correct, -0.5 wrong"},{"label":"Sections","value":"Reasoning, General Awareness, Quantitative Aptitude, English"}],
    topics: ["Quantitative Aptitude (arithmetic, algebra, geometry, data interpretation)","General Intelligence & Reasoning (analogies, series, syllogisms, coding-decoding)","English Comprehension (grammar, vocabulary, reading comprehension)","General Awareness (current affairs, history, geography, polity, economy, science)","Banking-specific: banking awareness, computer aptitude, and puzzles for IBPS/SBI"],
    tips: ["Master calculation speed early — learn tables, squares, cubes, and shortcut tricks so Quant and DI stop eating your time.","Read a daily current-affairs digest and revise weekly; General Awareness is scoring and needs no calculation.","Take full-length mocks under real 60-minute conditions, then analyse every mistake to fix weak areas.","Because of negative marking, only attempt questions you're reasonably sure about — accuracy beats blind guessing."],
  },
  {
    examSlug: "class-10",
    heading: "CBSE Class 10 Board Exams: Building Your Academic Foundation",
    paragraphs: ["The CBSE Class 10 board examination is the first major national-level exam an Indian student faces, conducted by the Central Board of Secondary Education at the end of secondary school. Your Class 10 result influences stream selection for Class 11 (Science, Commerce, or Humanities) and stays on your academic record for years, so a strong score opens doors.","It is taken by students across CBSE-affiliated schools in India and abroad. The assessment blends an 80-mark year-end board paper with 20 marks of internal assessment (periodic tests, practicals, and activities) in most subjects, so consistent classroom performance matters alongside the final exam.","PadhoDost supports Class 10 preparation with free chapter-wise practice tests aligned to the latest CBSE syllabus, full-length subject mocks, and instant scoring so you know exactly where you stand. Visual explainers turn hard chapters — like trigonometry, chemical reactions, and civics concepts — into clear, memorable diagrams, and your progress is tracked chapter by chapter."],
    pattern: [{"label":"Board","value":"CBSE (Central Board of Secondary Education)"},{"label":"Assessment split","value":"80 marks board exam + 20 marks internal"},{"label":"Duration","value":"3 hours per subject paper"},{"label":"Core subjects","value":"5 (plus optional 6th)"},{"label":"Passing marks","value":"33% in each subject"}],
    topics: ["Mathematics (real numbers, polynomials, trigonometry, coordinate geometry, statistics)","Science (Physics, Chemistry, Biology combined)","Social Science (History, Geography, Civics, Economics)","English (Language & Literature)","Second/third language (Hindi, Sanskrit, or others) plus optional subjects"],
    tips: ["Stick closely to NCERT textbooks — CBSE board papers are built directly from them, so master every solved example and exercise.","Solve previous years' papers and sample papers within the 3-hour time limit to build exam stamina and speed.","Don't ignore internal assessment — the 20 internal marks are easy points that lift your overall percentage.","Revise regularly in short cycles rather than cramming; make formula sheets and diagram notes for quick last-week revision."],
  },
  {
    examSlug: "jee",
    heading: "JEE Main & Advanced: The Path to IITs and NITs",
    paragraphs: ["The Joint Entrance Examination (JEE) is India's premier engineering entrance test. JEE Main, conducted by the National Testing Agency, is the gateway to NITs, IIITs, and other centrally funded technical institutes, and also serves as the qualifying exam for JEE Advanced. Only the top performers in JEE Main become eligible for JEE Advanced, which decides admission to the prestigious IITs.","Every year, well over a million students who have completed or are appearing in Class 12 with Physics, Chemistry, and Mathematics take JEE Main, making it one of the toughest and most competitive exams in the world. JEE Main is held in multiple sessions, and your best score counts.","PadhoDost helps you prepare with free full-length JEE mock tests that follow the real pattern and marking, topic-wise chapter practice across all three subjects, and an All-India rank so you can benchmark yourself against serious aspirants. Visual explainers make abstract ideas — rotational mechanics, organic reaction mechanisms, conic sections — intuitive, and detailed solutions help you learn from every attempt."],
    pattern: [{"label":"Subjects","value":"Physics, Chemistry, Mathematics"},{"label":"Total questions","value":"75 (25 per subject)"},{"label":"Total marks","value":"300"},{"label":"Duration","value":"3 hours"},{"label":"Marking","value":"+4 correct, -1 wrong (MCQs)"}],
    topics: ["Physics (mechanics, thermodynamics, electromagnetism, optics, modern physics)","Chemistry (physical, organic, and inorganic chemistry)","Mathematics (calculus, algebra, coordinate geometry, trigonometry, vectors)","Advanced problem-solving and multi-concept application for JEE Advanced","NCERT-based fundamentals across Class 11 and Class 12 syllabus"],
    tips: ["Build rock-solid concepts from NCERT first, then move to advanced problem practice — JEE rewards understanding, not rote learning.","Practise a large volume of varied problems and time yourself; speed and accuracy under pressure decide your rank.","Take full-length mocks regularly and analyse errors to separate silly mistakes from genuine concept gaps.","Balance all three subjects — neglecting even one drags your overall rank, since sectional performance matters."],
  },
  {
    examSlug: "neet",
    heading: "NEET: The Single Gateway to Medical Colleges in India",
    paragraphs: ["NEET (National Eligibility cum Entrance Test), conducted by the National Testing Agency, is the single national entrance exam for admission to MBBS, BDS, AYUSH, and other medical and dental courses across India. It is the only route to nearly every medical seat in the country, from government colleges to private and deemed universities.","Taken by well over a million aspirants each year — students who have completed Class 12 with Physics, Chemistry, and Biology — NEET is fiercely competitive, with rank determining which college and course you can secure. Biology carries the largest weight, making it the decisive subject for most toppers.","On PadhoDost you can take free full-length NEET mock tests built to the exact 180-question, 720-mark pattern, practise chapter-wise across Physics, Chemistry, and Biology, and track your All-India rank as you improve. Visual explainers bring diagrams-heavy topics like human physiology, genetics, and organic chemistry to life, and full solutions turn every mock into a learning session."],
    pattern: [{"label":"Total questions","value":"180 (attempt 180)"},{"label":"Total marks","value":"720"},{"label":"Duration","value":"3 hours 20 minutes"},{"label":"Marking","value":"+4 correct, -1 wrong"},{"label":"Subjects","value":"Physics, Chemistry, Botany, Zoology"}],
    topics: ["Biology — Botany and Zoology (genetics, human physiology, ecology, cell biology, biotechnology)","Chemistry (physical, organic, and inorganic chemistry)","Physics (mechanics, thermodynamics, electrodynamics, optics, modern physics)","NCERT Class 11 and Class 12 syllabus across all subjects","Diagram-based and application questions, especially in Biology"],
    tips: ["Treat NCERT Biology as your bible — memorise it line by line, because most NEET Biology questions come straight from it.","Give Biology the most practice since it carries half the marks and is the highest-scoring section.","Strengthen Physics with numerical practice — it's the toughest section for many and often decides top ranks.","Take timed full-length mocks to build the stamina needed for 3 hours 20 minutes, and review every wrong answer carefully."],
  },
];

export const getExamIntro = (slug: string) => examIntros.find((e) => e.examSlug === slug);
